-- Generated by LaunchProof — enable Row Level Security on tables that had none.
--
-- REVIEW BEFORE MERGING. This enables RLS and adds an owner-scoped SELECT
-- policy assuming a "user_id" column. If a table uses a different owner
-- column, or needs insert/update/delete policies, adjust before merging.
-- Enabling RLS with NO policy denies all access, so this adds a starter
-- policy rather than leaving the table locked.

alter table customer_secrets enable row level security;
create policy "customer_secrets_select_own" on customer_secrets for select using (auth.uid() = user_id);
